name: Generate snake animation

on:
  schedule:
    - cron: "*/6 * * * *"  # Trigger every 6 minutes
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Using latest stable version

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kesari46  # Your GitHub username
          outputs: dist/snake.svg?palette=github-dark

      - name: Verify if snake.svg exists
        run: |
          ls -l dist/snake.svg  # This will ensure the file is generated

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Ensure output branch exists
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #
